- name: Bootstrap Postgre
  hosts: miad_vms
  tasks:
  - name: Copy files
    ansible.builtin.copy:
      src: postgres
      dest: ~/
      directory_mode:
  - name: Change script permissions
    ansible.builtin.file:
      path: ~/postgres/scripts/
      mode: '0774'
      recurse: yes
  - name: Setup dirs and files
    ansible.builtin.shell: ~/postgres/scripts/bootstrap.sh
  - name: Copy docker-compose
    ansible.builtin.copy:
      src: "postgres/docker-compose.yml"
      dest: "postgres/docker-compose.yml"
  - name: Apply docker compose up
    ansible.builtin.shell: cd postgres && docker compose up -d